# Generated by Django 5.2.7 on 2025-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('warehouse_manager', 'Завскладом'), ('veterinarian', 'Ветеринар')], default='veterinarian', max_length=20)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
