# Generated by Django 5.2.7 on 2025-11-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('dosage_form', models.CharField(max_length=50, verbose_name='Форма выпуска')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Справочник препаратов',
            },
        ),
    ]
