# Generated by Django 5.2.7 on 2025-12-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20251205_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа препаратов',
                'verbose_name_plural': 'Группы препаратов',
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='drugs.druggroup'),
        ),
    ]
