# Generated by Django 5.2.7 on 2025-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('warehouse_supervisor', 'Заведующий складом'), ('veterinarian', 'Ветеринар')], default='veterinarian', max_length=50),
        ),
    ]
