# Generated by Django 5.2.7 on 2025-11-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeprofile_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeprofile',
            managers=[
            ],
        ),
    ]
