# Generated by Django 5.2.7 on 2025-12-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employeprofile_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeprofile',
            options={'permissions': [('open_task', 'can open task')]},
        ),
    ]
