# Generated by Django 5.2.7 on 2025-12-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employeprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeprofile',
            options={'permissions': [('close_task', 'can open task')]},
        ),
    ]
