# Generated by Django 5.2.7 on 2025-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employeprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeprofile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
