# Generated by Django 5.2.7 on 2025-12-07 20:57

import apps.users.roles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employeprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeprofile',
            name='role',
            field=models.CharField(choices=apps.users.roles.get_role_choices, default='', max_length=50),
        ),
    ]
