# Generated by Django 5.2.7 on 2025-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employeprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='employeprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('veterinarian', 'Ветеринар'), ('warehouseman', 'Кладовщик')], default='veterinarian', max_length=50),
        ),
    ]
