# Generated by Django 5.2.7 on 2025-12-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0003_druggroup_drug_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название секции')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код секции')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название склада')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Номер партии')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('expiry_date', models.DateField(verbose_name='Срок годности')),
                ('received_quantity', models.PositiveIntegerField(verbose_name='Количество при поступлении')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Локация')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='drugs.drug', verbose_name='Препарат')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='batches.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('drug_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='drugs.druggroup', verbose_name='Группа препаратов')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='InventorySessionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='batches.inventorysession', verbose_name='Сессия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_links', to='batches.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Секция в инвентаризации',
                'verbose_name_plural': 'Секции в инвентаризациях',
            },
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='inventory_sessions', through='batches.InventorySessionSection', to='batches.section', verbose_name='Секции'),
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField(verbose_name='Учётное количество')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество')),
                ('difference', models.IntegerField(blank=True, null=True, verbose_name='Расхождение')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='batches.batch', verbose_name='Партия')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='batches.inventorysession', verbose_name='Сессия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='batches.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Строка инвентаризации',
                'verbose_name_plural': 'Строки инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество в секции')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='batches.batch', verbose_name='Партия')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_links', to='batches.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Партия в секции',
                'verbose_name_plural': 'Партии по секциям',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='batches.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='batches.warehouse', verbose_name='Склад'),
        ),
        migrations.AddConstraint(
            model_name='inventorysessionsection',
            constraint=models.UniqueConstraint(fields=('session', 'section'), name='uniq_inventory_session_section'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['session'], name='batches_inv_session_49258d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['batch'], name='batches_inv_batch_i_4c5a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['section'], name='batches_inv_section_f31e0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.UniqueConstraint(fields=('session', 'batch', 'section'), name='uniq_inventory_line'),
        ),
        migrations.AddConstraint(
            model_name='batchsection',
            constraint=models.UniqueConstraint(fields=('batch', 'section'), name='uniq_batch_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name'), name='uniq_section_name_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('warehouse', 'code'), name='uniq_section_code_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['warehouse', 'status', 'started_at'], name='batches_inv_warehou_5a0e78_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('warehouse',), name='uniq_active_inventory_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['warehouse', 'batch_number'], name='batches_bat_warehou_05b9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='batches_bat_expiry__e6a609_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('drug', 'batch_number', 'warehouse'), name='uniq_batch_per_drug_wh'),
        ),

    ]
